config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :stores, only: [:show, :edit, :update, :create] do
    post 'store_vote', on: :member
    post 'comments', on: :member
    post 'bookmark', on: :member
  end

  resources :comments, only: [:destroy] do
    post 'comment_vote', on: :member
  end

  resources :s, only: [:index]
  post 's', to: 's#search'
  resources :photo_uploads, only: [:create, :destroy]
  get 'create-a-store', to: 'stores#create_a_store'
  put 'create-a-store', to: 'stores#update_create_a_store'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %> alert-dismissible fade show" role="alert">
    <strong><%= value %></strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if defined?(resource) && resource.errors.any? %>
  <% resource.errors.full_messages.each do |message| %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong><%= message %></strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.erb
<!-- Footer-->
<footer class="position-relative z-index-10">
  <!-- Main block - menus, subscribe form-->
  <div class="py-6 bg-gray-200 text-muted">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h6 class="text-uppercase text-dark mb-3"><%= t('daily_discounts') %></h6>
          <form action="#" id="newsletter-form">
            <div class="input-group mb-3">
              <input type="email" placeholder="<%= t('your_email') %>" aria-label="Your Email Address" class="form-control bg-transparent border-dark border-right-0">
              <div class="input-group-append">
                <button type="submit" class="btn btn-outline-dark border-left-0"> <i class="fa fa-paper-plane text-lg"></i></button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- Copyright section of the footer-->
  <div class="py-4 font-weight-light bg-gray-800 text-gray-300">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-6 text-center text-md-left">
          <p class="text-sm mb-md-0">&copy; <%= Time.now.year.to_s %> <%= t(:all_rights_reserved) %>.</p>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- /Footer-->

app/views/shared/_navbar.html.erb
<%= javascript_pack_tag 'locales' %>

<!-- Navbar-->
<nav class="navbar navbar-expand-lg shadow navbar-light bg-white">
  <div class="container-fluid">
    <div class="d-flex align-items-center">
      <%= link_to image_tag("logo.svg", alt: "SentryCity Logo"), root_path ,class: "navbar-brand py-1" %>
      <a id="locale-chinese" onClick="custom.setLocales(event, 'zh')"><span class="badge badge-danger ml-1">繁</span></a>
      <a id="locale-english" onClick="custom.setLocales(event, 'en')"><span class="badge badge-info ml-1">English</span></a>
    </div>
    <button type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler navbar-toggler-right"><i class="fa fa-bars"></i></button>
    <!-- Navbar Collapse -->
    <div id="navbarCollapse" class="collapse navbar-collapse">
      <form action="#" id="searchcollapsed" class="form-inline mt-4 mb-2 d-sm-none">
        <div class="input-label-absolute input-label-absolute-left input-reset w-100">
          <label for="searchcollapsed_search" class="label-absolute"><i class="fa fa-search"></i><span class="sr-only">What are you looking for?</span></label>
          <input id="searchcollapsed_search" placeholder="Search" aria-label="Search" class="form-control form-control-sm border-0 shadow-0 bg-gray-200">
          <button type="reset" class="btn btn-reset btn-sm"><i class="fa-times fas">           </i></button>
        </div>
      </form>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a href="/s?search_params[district_ids][]=1" class="nav-link"><%= t(:search) %></a> </li>
        <% if current_user %>
          <li class="nav-item"><%= link_to t(:sign_out), destroy_user_session_path, class: "nav-link", method: :delete %></li>
        <% else %>
          <li class="nav-item"><a href="#" data-toggle="modal" data-target="#signinModal" class="nav-link"><%= t(:sign_in) %></a></li>
        <% end %>

        <li class="nav-item mt-3 mt-lg-0 ml-lg-3 d-xl-inline-block"><a href="/create-a-store" class="btn btn-primary"><%= t(:add_a_store_sale) %></a></li>
      </ul>
    </div>
  </div>
</nav>
<!-- /Navbar -->

app/views/shared/_signin_modal.html.erb
<!-- Modal-->
<div id="signinModal" tabindex="-1" role="dialog" aria-labelledby="signinModalLabel" aria-hidden="true" class="modal fade">
  <div role="document" class="modal-dialog">
    <div class="modal-content">
      <div class="w-100 py-5 px-md-5 px-xl-5 px-4 position-relative">
        <div class="mb-5"><img src="<%= asset_path('logo-square.svg') %>" alt="SentryCity Logo" style="max-width: 4rem;" class="img-fluid mb-3">
          <h2><%= t('devise.sessions.new.welcome') %></h2>
        </div>
        <%= form_for(:user, as: :user, url: session_path(:user), html: { class: "form-validate" }) do |f| %>
          <div class="form-group">
            <%= f.label t('devise.sessions.new.welcome'), class: "form-label" %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", id: 'modal_user_email' %>
          </div>

          <div class="form-group mb-4">
            <div class="row">
              <div class="col">
                <%= f.label t('devise.sessions.new.password'), class: "form-label" %>
              </div>
              <div class="col-auto">
                <%= link_to t('devise.sessions.new.forgot_password'), new_password_path(:user), class: "form-text small" %>
              </div>
            </div>
            <%= f.password_field :password, autocomplete: "current-password", class: "form-control", id: 'modal_user_password' %>
          </div>

          <div class="form-group mb-4">
            <div class="custom-control custom-checkbox">
              <%= f.check_box :remember_me, class: "custom-control-input", id: 'modal_user_remember_me' %>
              <%= f.label t('devise.sessions.new.remember_me'), class: "custom-control-label text-muted" %>
            </div>
          </div>

          <%= f.submit t('devise.sessions.new.sign_in'), class: "btn btn-lg btn-block btn-primary" %>
          <hr data-content="<%= t('devise.sessions.new.or') %>" class="my-3 hr-text letter-spacing-2">

        <% end %>
        <form action="<%= user_facebook_omniauth_authorize_path %>">
          <button class="btn btn btn-outline-primary btn-block btn-social mb-3"><i class="fa-2x fa-facebook-f fab btn-social-icon"> </i><%= t('devise.sessions.new.facebook_login') %></button>
        </form>
        <hr class="my-4">
        <p class="text-center">
          <small class="text-muted text-center">
            <%= t('devise.sessions.new.no_account_yet') %> <%= link_to "Sign Up", new_registration_path(:user) %>
          </small><br />
          <small class="text-muted text-center">
            <%= link_to t('devise.sessions.new.did_not_receive_confirmation_industructions'), new_confirmation_path(:user) %>
          </small><br />
          <small class="text-muted text-center">
            <%= link_to t('devise.sessions.new.did_not_receive_unlock_industructions'), new_unlock_path(:user) %>
          </small><br />
        </p>
      </div>
    </div>
  </div>
</div>
<!-- /Modal-->