config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :stores, only: [:show, :edit, :update, :create] do
    post 'store_vote', on: :member
    post 'comments', on: :member
    post 'bookmark', on: :member
  end

  resources :comments, only: [:destroy] do
    post 'comment_vote', on: :member
  end

  resources :s, only: [:index]
  post 's', to: 's#search'
  resources :photo_uploads, only: [:create, :destroy]
  get 'create-a-store', to: 'stores#create_a_store'
  put 'create-a-store', to: 'stores#update_create_a_store'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/models/store.rb
# == Schema Information
#
# Table name: stores
#
#  id          :bigint(8)        not null, primary key
#  name        :string(255)
#  event_type  :string(255)
#  event_date  :datetime
#  address     :string(255)
#  lat         :decimal(10, 6)
#  lng         :decimal(10, 6)
#  description :text(65535)
#  bhours_0    :string(255)
#  bhours_1    :string(255)
#  bhours_2    :string(255)
#  bhours_3    :string(255)
#  bhours_4    :string(255)
#  bhours_5    :string(255)
#  bhours_6    :string(255)
#  bhours_7    :string(255)
#  phone       :string(255)
#  url         :text(65535)
#  state       :string(255)      default("draft"), not null
#  user_id     :bigint(8)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  discount    :string(255)
#  district_id :bigint(8)
#

class Store < ApplicationRecord
  FAREWELL = 'Farewell Sale'
  GRAND_OPENING = 'Grand Opening'

  include Votable
  include Sellable
  include Commentable
  include Bookmarkable
  include Filterable

  scope :search_text, -> (search_text) { where("stores.name LIKE ?", "%#{sanitize_sql_like(search_text)}%") }
  scope :district_ids, -> (district_ids) { where(district_id: district_ids) }
  scope :tag_ids, -> (tag_ids) { includes(:tags).where(tags: { id: tag_ids }) }
  scope :event_types, -> (event_types) { where(event_type: event_types) }

  validates_presence_of :state

  has_many_attached :photos
  belongs_to :user, inverse_of: :stores
  belongs_to :district, inverse_of: :stores, optional: true
  has_many :goods_stores, inverse_of: :store
  has_many :goods, through: :goods_stores
  has_many :comments, -> { order("created_at DESC") }, inverse_of: :store
  has_many :bookmarks, inverse_of: :store
  has_many :votes, inverse_of: :votable, as: :votable
  has_many :stores_tags, inverse_of: :store
  has_many :tags, through: :stores_tags

  def farewell_sale?
    self.event_type == FAREWELL
  end

  def grand_opening?
    self.event_type == GRAND_OPENING
  end

  def self.format_bhours(original_hours)
    return nil unless original_hours.present?
    open, close = original_hours.split(';')
    open = open + ':00'
    close = close + ':00'
    open + ' - ' + close
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :require_login

  def bookmark
    @store = Store.find(params[:id])
    if @store.user == current_user
      @store.bookmark_toggle(current_user.id)
    else
      render js: {}, status: 401
    end
  end

  def comments
    @store = Store.find(params[:id])
    comment = Comment.new(comment_params)
    comment.user = current_user
    @store.comments << comment
  end

  def create_a_store(t_no = nil)
    @store = Store.find_or_create_by(user: current_user, state: 'draft')
    step = params[:step].nil? ? 0 : params[:step].to_i - 1
    @template_no = t_no ? t_no : [1, 2, 3, 4, 5][step]
  end

  def show
    @store = Store.includes(comments: :user).find(params[:id])
    @vote_count = @store.vote_count
  end

  def store_vote
    @store = Store.find(params[:id])
    if vote_params[:vote] == "1"
      @store.up_vote(current_user.id)
    elsif vote_params[:vote] == "-1"
      @store.down_vote(current_user.id)
    end

    @new_vote_count = @store.vote_count
  end

  def update_create_a_store
    if @store = Store.find_by(user: current_user, state: 'draft')
      @store.update(update_store_params)
      @store.update(state: 'active') if next_form_no_params == 5
    else
      render js: {}, status: 404
    end
    create_a_store(next_form_no_params)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def next_form_no_params
    params.require(:next_form_no)
  end

  def update_store_params
    params.
      require(:store_params).
      permit(
        :name,
        :event_date,
        :event_type,
        :district_id,
        :address,
        :description,
        :discount,
        :bhours_0,
        :bhours_1,
        :bhours_2,
        :bhours_3,
        :bhours_4,
        :bhours_5,
        :bhours_6,
        :bhours_7,
        :phone,
        :url,
        :lat,
        :lng,
        tag_ids: []
      )
  end

  def vote_params
    params.require(:store_vote).permit(:vote)
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/create_a_store/_create_a_store_1.html.erb
<style>
  /* Always set the map height explicitly to define the size of the div
    * element that contains the map. */
  #map {
    height: 300px;
    width: 100%;
  }
  /* Optional: Makes the sample page fill the window. */

  #infowindow-content .title {
    font-weight: bold;
  }

  #infowindow-content {
    display: none;
  }

  #map #infowindow-content {
    display: inline;
  }

  #pac-container {
    padding-bottom: 12px;
    margin-right: 12px;
  }

  #pac-input {
    background-color: #fff;
    font-size: 15px;
    font-weight: 300;
    margin-left: 12px;
    padding: 0 11px 0 13px;
    text-overflow: ellipsis;
    width: 400px;
  }

  #pac-input:focus {
    border-color: #4d90fe;
  }
</style>

<div style="height: 8px; top: 71px;" class="progress rounded-0">
  <div role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" class="progress-bar"></div>
</div>
<section class="py-5">
  <div class="container">
    <p class="subtitle text-primary"><%= t('.add_new_listing') %></p>
    <h1 class="h2 mb-5"> <%= t('.basic_info') %> <span class="text-muted float-right"><%= t('.step_1') %></span></h1>
    <form action="/create-a-store" method="post" id="create-a-store-form">
      <input type="hidden" name="authenticity_token" value="token_value">
      <input name="_method" type="hidden" value="put" />
      <div class="row form-block">
        <div class="col-lg-4">
          <h4><%= t('.basic') %></h4>
          <p class="text-muted text-sm">His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread out on the table.</p>
        </div>
        <div class="col-lg-7 ml-auto">
          <div class="form-group">
            <label class="form-label"><%= t('.grand_opening_or_farewell_sale') %></label>
            <div class="custom-control custom-radio">
              <input value="Farewell Sale" <%= store.event_type && store.event_type == "Farewell Sale" ? "checked" : "" %> <%= store.event_type.nil? ? "checked" : "" %> type="radio" id="event-type-farewell-sale" name="store_params[event_type]" class="custom-control-input">
              <label for="event-type-farewell-sale" class="custom-control-label"><%= t('.farewell_sale') %></label>
            </div>
            <div class="custom-control custom-radio">
              <input value="Grand Opening" <%= store.event_type && store.event_type == "Grand Opening" ? "checked" : "" %> type="radio" id="event-type-grand-opening" name="store_params[event_type]" class="custom-control-input">
              <label for="event-type-grand-opening" class="custom-control-label"><%= t('.grand_opening') %></label>
            </div>
          </div>
          <div class="form-group">
            <label for="store-name" class="form-label"><%= t('.store_name') %></label>
            <input name="store_params[name]" id="store-name" class="form-control" value="<%= store.name %>">
          </div>
          <div class="form-group">
            <label for="event-date" class="form-label"><%= t('.date_of_event') %></label>
            <input value="<%= store.event_date && store.event_date.strftime("%Y-%m-%d") %>" type="date" name="store_params[event_date]" id="event-date" class="form-control col-lg-4">
          </div>
        </div>
      </div>
      <div class="row form-block">
        <div class="col-lg-4">
          <h4><%= t('.location') %></h4>
          <p class="text-muted text-sm">Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame.</p>
        </div>
        <div class="col-lg-7 ml-auto">
          <!-- District-->
          <div class="form-group">
            <label for="district" class="form-label"><%= t('.district') %></label></br>
            <select name="store_params[district_id]" id="district" data-style="btn-selectpicker" title=" " data-live-search="true" class="selectpicker form-control col-lg-4">
              <% District.all.each do |district| %>
                <option <%= store.district_id == district.id ? "selected" : "" %> value="<%= district.id %>"><%= t("app-settings.districts.#{district.name}") %></option>
              <% end %>
            </select>
          </div>
          <!-- Address-->
          <div class="form-group">
            <label for="address" class="form-label"><%= t('.address') %></label>
            <input style="margin: 0;" value="<%= store.address %>" name="store_params[address]" id="pac-input" class="form-control" type="text">
            <input type="hidden" id="lat" name="store_params[lat]" value="<%= store.lat %>">
            <input type="hidden" id="lng" name="store_params[lng]" value="<%= store.lng %>">
          </div>
        </div>
      </div>
      <!-- Map -->
      <div id="map"></div>
      <div id="infowindow-content">
        <img src="" width="16" height="16" id="place-icon">
        <span id="place-name"  class="title"></span><br>
        <span id="place-address"></span>
      </div>
      <div class="row form-block flex-column flex-sm-row">
        <div class="col text-center text-sm-left"></div>
        <div class="col text-center text-sm-right"><button name="next_form_no" value="2" class="btn btn-primary px-3"><%= t('.next_step') %><i class="fa-chevron-right fa ml-2"></i></button></div>
      </div>
    </form>
  </div>
</section>

<script>
  // This example requires the Places library. Include the libraries=places
  // parameter when you first load the API. For example:
  // <script src="https://maps.googleapis.com/maps/api/js?key=YOURKEY&libraries=places">

  function initMap() {
    var map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: <%= store.lat || 22.277162 %>, lng: <%= store.lng || 114.1712311 %>},
      zoom: 16,
      disableDefaultUI: true,
      gestureHandling: 'none',
      zoomControl: false
    });
    var input = document.getElementById('pac-input');
    var autocomplete = new google.maps.places.Autocomplete(input);

    // Bind the map's bounds (viewport) property to the autocomplete object,
    // so that the autocomplete requests use the current map bounds for the
    // bounds option in the request.
    autocomplete.bindTo('bounds', map);

    // Set the data fields to return when the user selects a place.
    autocomplete.setFields(
        ['address_components', 'geometry', 'icon', 'name']);

    var infowindow = new google.maps.InfoWindow();
    var infowindowContent = document.getElementById('infowindow-content');
    infowindow.setContent(infowindowContent);
    var marker = new google.maps.Marker({
      map: map,
      anchorPoint: new google.maps.Point(0, -29)
    });


    if (input.value !== '') {
      var request = {
        query: input.value,
        fields: ['geometry', 'icon', 'name']
      };

      var service = new google.maps.places.PlacesService(map);

      service.findPlaceFromQuery(request, function(results, status) {
        var place = results[0];
        if (!place.geometry) {
          // User entered the name of a Place that was not suggested and
          // pressed the Enter key, or the Place Details request failed.
          window.alert("No details available for input: '" + place.name + "'");
          return;
        }

        // If the place has a geometry, then present it on a map.
        if (place.geometry.viewport) {
          map.fitBounds(place.geometry.viewport);
        } else {
          map.setCenter(place.geometry.location);
          map.setZoom(17);  // Why 17? Because it looks good.
        }
        marker.setPosition(place.geometry.location);
        marker.setVisible(true);

        infowindowContent.children['place-icon'].src = place.icon;
        infowindowContent.children['place-name'].textContent = place.name;
        infowindowContent.children['place-address'].textContent = input.value;
        infowindow.open(map, marker);
      });
    }

    google.maps.event.trigger(autocomplete, 'place_changed')

    autocomplete.addListener('place_changed', function() {
      infowindow.close();
      marker.setVisible(false);
      var place = autocomplete.getPlace();
      console.log(place)
      $('input[name="store_params[lat]"').val(place.geometry.location.lat());
      $('input[name="store_params[lng]"').val(place.geometry.location.lng());
      if (!place.geometry) {
        // User entered the name of a Place that was not suggested and
        // pressed the Enter key, or the Place Details request failed.
        window.alert("No details available for input: '" + place.name + "'");
        return;
      }

      // If the place has a geometry, then present it on a map.
      if (place.geometry.viewport) {
        map.fitBounds(place.geometry.viewport);
      } else {
        map.setCenter(place.geometry.location);
        map.setZoom(17);  // Why 17? Because it looks good.
      }
      marker.setPosition(place.geometry.location);
      marker.setVisible(true);

      var address = '';
      if (place.address_components) {
        address = [
          (place.address_components[0] && place.address_components[0].short_name || ''),
          (place.address_components[1] && place.address_components[1].short_name || ''),
          (place.address_components[2] && place.address_components[2].short_name || '')
        ].join(' ');
      }

      infowindowContent.children['place-icon'].src = place.icon;
      infowindowContent.children['place-name'].textContent = place.name;
      infowindowContent.children['place-address'].textContent = address;
      infowindow.open(map, marker);
    });
  }
</script>
<% if Rails.env == 'production' %>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google[:key] %>&libraries=places&callback=initMap" async defer></script>
<% end %>

app/views/stores/create_a_store/_create_a_store_2.html.erb
<div style="height: 8px; top: 71px;" class="progress rounded-0">
  <div role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" class="progress-bar"></div>
</div>
<section class="py-5">
  <div class="container">
    <p class="subtitle text-primary"><%= t('.add_new_listing') %></p>
    <h1 class="h2 mb-5"> <%= t('.store_type') %> <span class="text-muted float-right"><%= t('.step_2') %></span>                </h1>
    <form action="/create-a-store" method="post" id="create-a-store-form">
      <input type="hidden" name="authenticity_token" value="token_value">
      <input name="_method" type="hidden" value="put" />
      <div class="row form-block">
          <div class="col-lg-4">
            <h4><%= t('.what_does_the_store_sell') %></h4>
            <p class="text-muted text-sm">His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread out on the table.</p>
          </div>
          <div class="col-lg-7 ml-auto">
            <div class="form-group">
              <label class="form-label"><%= t('.goods') %></label>
              <ul class="list-inline mb-0">
                <% Tag.all.each do |tag| %>
                  <li class="list-inline-item">
                    <div class="custom-control custom-checkbox">
                      <%= hidden_field_tag "store_params[tag_ids][]", nil %>
                      <input <%= store.tags.map(&:id).include?(tag.id) ? "checked" : "" %> type="checkbox" id="tag-id-<%= tag.id %>" name="store_params[tag_ids][]" value="<%= tag.id %>" class="custom-control-input">
                      <label for="tag-id-<%= tag.id %>" class="custom-control-label text-muted"><%= t("app-settings.goods_types.#{tag.name}") %></label>
                    </div>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      <div class="row form-block">
          <div class="col-lg-4">
            <h4><%= t('.up_to_off') %></h4>
            <p class="text-muted text-sm">His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread out on the table.</p>
          </div>
          <div class="col-lg-7 ml-auto">
            <div class="col-lg-12">
              <label class="form-label"><%= t('.add_new_listing') %></label>
              <div class="d-flex align-items-center">
                <input type="text" class="js-range-slider" name="store_params[discount]" style="width: 100%;"
                  data-skin="round"
                  data-postfix="%"
                  data-step="5"
                  data-min="5"
                  data-max="95"
                  data-from="<%= store.discount ? store.discount : '30' %>"
                  data-grid="true" />
              </div>
            </div>
          </div>
        </div>
      <div class="row form-block">
        <div class="col-lg-4">
          <h4><%= t('.description') %></h4>
          <p class="text-muted text-sm"> Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame.</p>
        </div>
        <div class="col-lg-7 ml-auto">
          <div class="form-group mb-5">
            <label for="description" class="form-label"><%= t('.help_shoppers') %></label>
            <textarea name="store_params[description]" id="description" rows="5" aria-describedby="descriptionHelp" class="form-control"><%= store.description %></textarea><small id="descriptionHelp" class="form-text text-muted mt-2"><%= t('.example') %></small>
          </div>
        </div>
      </div>
      <div class="row form-block flex-column flex-sm-row">
        <div class="col text-center text-sm-left"><button name="next_form_no" value="1" onClick="custom.updateStore(event)" href="create-a-store?step=1" class="btn btn-link text-muted"><i class="fa-chevron-left fa mr-2"></i><%= t('.back') %></button></div>
        <div class="col text-center text-sm-right"><button name="next_form_no" value="3" class="btn btn-primary px-3"><%= t('.next_step') %><i class="fa-chevron-right fa ml-2"></i></button></div>
      </div>
    </form>
  </div>
</section>

<!--Plugin CSS file with desired skin-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.0/css/ion.rangeSlider.min.css"/>

<!--jQuery-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!--Plugin JavaScript file-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.0/js/ion.rangeSlider.min.js"></script>

<script>$(".js-range-slider").ionRangeSlider();</script>

app/views/stores/create_a_store/_create_a_store_3.html.erb
<div style="height: 8px; top: 71px;" class="progress rounded-0">
  <div role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" class="progress-bar"></div>
</div>
<section class="py-5">
  <div class="container">
    <p class="subtitle text-primary"><%= t('.add_new_listing') %></p>
    <h1 class="h2 mb-5"> <%= t('.business_hours') %> <span class="text-muted float-right"><%= t('.step_3') %></span>                </h1>
    <form action="/create-a-store" method="post" id="create-a-store-form">
      <input type="hidden" name="authenticity_token" value="token_value">
      <input name="_method" type="hidden" value="put" />
      <div class="row form-block">
        <div class="col-lg-4">
          <h4><%= t('.when_open_close') %></h4>
          <p class="text-muted text-sm">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing elit duis tristique sollicitudin nibh sit. Est placerat in egestas erat imperdiet sed. Felis bibendum ut tristique et egestas quis.</p>
        </div>
        <div class="col-lg-7 ml-auto">
          <div class="row">
            <div class="col-lg-12">
              <label class="form-label"><%= t('app-settings.mondays') %></label>
              <div class="d-flex align-items-center">
                <input type="text" class="js-range-slider" name="store_params[bhours_0]" value="" style="width: 100%;"
                  data-type="double"
                  data-skin="round"
                  data-step="1"
                  data-min="0"
                  data-max="24"
                  data-from="<%= store.bhours_0 ? store.bhours_0.split(';').first : 9 %>"
                  data-to="<%= store.bhours_0 ? store.bhours_0.split(';').last : 22 %>"
                  data-grid="true" />
              </div>
            </div>
            <div class="col-lg-12">
              <label class="form-label"><%= t('app-settings.tuesdays') %></label>
              <div class="d-flex align-items-center">
                <input type="text" class="js-range-slider" name="store_params[bhours_1]" value="" style="width: 100%;"
                  data-type="double"
                  data-skin="round"
                  data-step="1"
                  data-min="0"
                  data-max="24"
                  data-from="<%= store.bhours_1 ? store.bhours_1.split(';').first : 9 %>"
                  data-to="<%= store.bhours_1 ? store.bhours_1.split(';').last : 22 %>"
                  data-grid="true" />
              </div>
            </div>
            <div class="col-lg-12">
              <label class="form-label"><%= t('app-settings.wednesdays') %></label>
              <div class="d-flex align-items-center">
                <input type="text" class="js-range-slider" name="store_params[bhours_2]" value="" style="width: 100%;"
                  data-type="double"
                  data-skin="round"
                  data-step="1"
                  data-min="0"
                  data-max="24"
                  data-from="<%= store.bhours_2 ? store.bhours_2.split(';').first : 9 %>"
                  data-to="<%= store.bhours_2 ? store.bhours_2.split(';').last : 22 %>"
                  data-grid="true" />
              </div>
            </div>
            <div class="col-lg-12">
              <label class="form-label"><%= t('app-settings.thursdays') %></label>
              <div class="d-flex align-items-center">
                <input type="text" class="js-range-slider" name="store_params[bhours_3]" value="" style="width: 100%;"
                  data-type="double"
                  data-skin="round"
                  data-step="1"
                  data-min="0"
                  data-max="24"
                  data-from="<%= store.bhours_3 ? store.bhours_3.split(';').first : 9 %>"
                  data-to="<%= store.bhours_3 ? store.bhours_3.split(';').last : 22 %>"
                  data-grid="true" />
              </div>
            </div>
            <div class="col-lg-12">
              <label class="form-label"><%= t('app-settings.fridays') %></label>
              <div class="d-flex align-items-center">
                <input type="text" class="js-range-slider" name="store_params[bhours_4]" value="" style="width: 100%;"
                  data-type="double"
                  data-skin="round"
                  data-step="1"
                  data-min="0"
                  data-max="24"
                  data-from="<%= store.bhours_4 ? store.bhours_4.split(';').first : 9 %>"
                  data-to="<%= store.bhours_4 ? store.bhours_4.split(';').last : 22 %>"
                  data-grid="true" />
              </div>
            </div>
            <div class="col-lg-12">
              <label class="form-label"><%= t('app-settings.saturdays') %></label>
              <div class="d-flex align-items-center">
                <input type="text" class="js-range-slider" name="store_params[bhours_5]" value="" style="width: 100%;"
                  data-type="double"
                  data-skin="round"
                  data-step="1"
                  data-min="0"
                  data-max="24"
                  data-from="<%= store.bhours_5 ? store.bhours_5.split(';').first : 9 %>"
                  data-to="<%= store.bhours_5 ? store.bhours_5.split(';').last : 22 %>"
                  data-grid="true" />
              </div>
            </div>
            <div class="col-lg-12">
              <label class="form-label"><%= t('app-settings.sundays') %></label>
              <div class="d-flex align-items-center">
                <input type="text" class="js-range-slider" name="store_params[bhours_6]" value="" style="width: 100%;"
                  data-type="double"
                  data-skin="round"
                  data-step="1"
                  data-min="0"
                  data-max="24"
                  data-from="<%= store.bhours_6 ? store.bhours_6.split(';').first : 9 %>"
                  data-to="<%= store.bhours_6 ? store.bhours_6.split(';').last : 22 %>"
                  data-grid="true" />
              </div>
            </div>
            <div class="col-lg-12">
              <label class="form-label"><%= t('app-settings.holidays') %></label>
              <div class="d-flex align-items-center">
                <input type="text" class="js-range-slider" name="store_params[bhours_7]" value="" style="width: 100%;"
                  data-type="double"
                  data-skin="round"
                  data-step="1"
                  data-min="0"
                  data-max="24"
                  data-from="<%= store.bhours_7 ? store.bhours_7.split(';').first : 9 %>"
                  data-to="<%= store.bhours_7 ? store.bhours_7.split(';').last : 22 %>"
                  data-grid="true" />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row form-block flex-column flex-sm-row">
        <div class="col text-center text-sm-left"><button name="next_form_no" value="2" class="btn btn-link text-muted"><i class="fa-chevron-left fa mr-2"></i><%= t('.back') %></button></div>
        <div class="col text-center text-sm-right"><button name="next_form_no" value="4" class="btn btn-primary px-3"><%= t('.next_step') %><i class="fa-chevron-right fa ml-2"></i></button></div>
      </div>
    </form>
  </div>
</section>

<!--Plugin CSS file with desired skin-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.0/css/ion.rangeSlider.min.css"/>

<!--jQuery-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!--Plugin JavaScript file-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.0/js/ion.rangeSlider.min.js"></script>

<script>$(".js-range-slider").ionRangeSlider();</script>

app/views/stores/create_a_store/_create_a_store_5.html.erb
<div style="height: 8px; top: 71px;" class="progress rounded-0">
  <div role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" class="progress-bar"></div>
</div>
<section class="py-5 py-lg-6">
  <div class="container text-center">
    <p class="subtitle text-primary"><%= t('.add_new_listing') %></p>
    <h1 class="h2 mb-5"><%= t('.listing_uploaded') %></h1>
    <p class="mb-5"><%= image_tag('celebration.svg', style: "width: 400px;", class: "img-fluid") %></p>
    <p class="text-muted mb-5"><%= t('.thank_you') %>, <%= current_user.name || current_user.email %>. <%= t('.reviewed_shortly') %></p>
    <p class="mb-5"><%= link_to(t('.see_your_listing'), store_path(current_user.stores.last), class: "btn btn-primary mr-2 mb-2") %>
  </div>
</section>

app/views/stores/create_a_store/_gallery.html.erb
<!-- Gallery-->
<h3 class="mb-4"><%= t('.gallery') %></h3>
<div class="row ml-n1 mr-n1">
  <% store.photos.each do |photo| %>
    <div class="col-lg-4 col-6 px-1 mb-2">
      <%= link_to image_tag(photo, class: "img-fluid"), photo_upload_path(photo.id), method: :delete, remote: true, data: {confirm: "Would you like to delete this photo?"} %>
    </div>
  <% end %>
</div>